name: Requested

on:
  workflow_run:
    workflows:
      - Hello
    types:
      - requested

jobs:
  on-requested:
    name: On Requested
    runs-on: ubuntu-latest
    steps:
      - run: echo 'The triggering workflow failed'