name: Requested

on:
  workflow_run:
    workflows:
      - Hello
    types:
      - requested

jobs:
  on-requested:
    name: On Requested
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == '' }}
    steps:
      - run: echo 'The triggering requested'