name: Requested

on:
  workflow_run:
    workflows:
      - Hello
    types:
      - requested

jobs:
  on-requested:
    name: On Requested
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == '' }}
    steps:
      - name: Call Hello World
        uses: docker://alpine:latest
        with:
          entrypoint: /bin/echo
          args: Hello, World From On Requested!